### STAGE 1: Build ###

FROM node:8.16.0-jessie as builder

# Preparing working environment.
RUN mkdir -p /usr/src/alerts-demo
WORKDIR /usr/src/alerts-demo

# Installing dependencies.
COPY package*.json /usr/src/alerts-demo/
RUN npm install

# Copy alerts-demo source into image.
COPY . /usr/src/alerts-demo

# Building app.
RUN npm run-script build

### STAGE 2: Setup ###

FROM nginx:1.13.12-alpine

# Removing nginx default page.
RUN rm -rf /usr/share/nginx/html/*

# Copying nginx configuration.
COPY /nginx/nginx.conf /etc/nginx/conf.d/default.conf

# Copying alerts-demo source into web server root.
COPY --from=builder /usr/src/alerts-demo/src /usr/share/nginx/html

# Exposing ports.
EXPOSE 8080

# Starting server.
CMD ["nginx", "-g", "daemon off;"]
